[package]
name = "rust-gpx"
version = "0.1.0"
authors = ["Cameron Lind <mediocresurgeon@gmail.com>"]

[workspace]

[dependencies]
geodesics = { path = "geodesics" }
serialization = { path = "serialization" }